import type {
  CanaryStage,
  DagGraphData,
  ErrorPattern,
  KnowledgeBaseRecord,
  LiveMetric,
  NodeComparison,
  PluginCompatibilityItem,
  PromptDiffData,
  ReviewItem,
  RollbackVersion,
  StructureDiffItem,
  TestCase,
  VariableMapping,
  WorkflowSummary,
} from "./types";

export const WORKFLOWS: WorkflowSummary[] = [
  {
    id: "wf1",
    name: "智能客服助手",
    cozeId: "bot_abc123",
    difyId: "app-xyz789",
    status: "migrated",
    nodes: 12,
    migrated: 11,
    failed: 1,
    score: 91.7,
    complexity: "high",
    lastSync: "2026-03-11",
  },
  {
    id: "wf2",
    name: "数据分析 Pipeline",
    cozeId: "bot_def456",
    difyId: "app-uvw321",
    status: "testing",
    nodes: 8,
    migrated: 8,
    failed: 0,
    score: 98.5,
    complexity: "medium",
    lastSync: "2026-03-12",
  },
  {
    id: "wf3",
    name: "文档摘要生成器",
    cozeId: "bot_ghi789",
    difyId: null,
    status: "pending",
    nodes: 6,
    migrated: 0,
    failed: 0,
    score: 0,
    complexity: "low",
    lastSync: null,
  },
  {
    id: "wf4",
    name: "多轮对话引擎",
    cozeId: "bot_jkl012",
    difyId: "app-rst654",
    status: "verified",
    nodes: 18,
    migrated: 18,
    failed: 0,
    score: 99.2,
    complexity: "high",
    lastSync: "2026-03-10",
  },
  {
    id: "wf5",
    name: "RAG 知识库问答",
    cozeId: "bot_mno345",
    difyId: "app-opq987",
    status: "failed",
    nodes: 15,
    migrated: 10,
    failed: 5,
    score: 66.7,
    complexity: "high",
    lastSync: "2026-03-12",
  },
];

export const DAG_COZE: DagGraphData = {
  nodes: [
    { id: "c1", type: "start", label: "用户输入", x: 60, y: 160 },
    { id: "c2", type: "llm", label: "意图识别", x: 220, y: 90 },
    { id: "c3", type: "knowledge", label: "知识库", x: 220, y: 230 },
    { id: "c4", type: "condition", label: "路由", x: 400, y: 160 },
    { id: "c5", type: "code", label: "数据处理", x: 560, y: 90 },
    { id: "c6", type: "http", label: "CRM API", x: 560, y: 230 },
    { id: "c7", type: "llm", label: "回复生成", x: 720, y: 160 },
    { id: "c8", type: "end", label: "输出", x: 870, y: 160 },
  ],
  edges: [
    ["c1", "c2"],
    ["c1", "c3"],
    ["c2", "c4"],
    ["c3", "c4"],
    ["c4", "c5"],
    ["c4", "c6"],
    ["c5", "c7"],
    ["c6", "c7"],
    ["c7", "c8"],
  ],
};

export const DAG_DIFY: DagGraphData = {
  nodes: [
    { id: "d1", type: "start", label: "开始", x: 50, y: 160 },
    { id: "d2", type: "llm", label: "意图分类", x: 190, y: 90 },
    { id: "d3", type: "knowledge", label: "知识检索", x: 190, y: 230 },
    { id: "d4", type: "condition", label: "IF/ELSE", x: 350, y: 160 },
    { id: "d5", type: "code", label: "代码执行", x: 500, y: 90 },
    { id: "d6", type: "http", label: "HTTP请求", x: 500, y: 230 },
    { id: "d7", type: "variable", label: "变量聚合", x: 640, y: 160 },
    { id: "d8", type: "llm", label: "LLM生成", x: 790, y: 160 },
    { id: "d9", type: "end", label: "结束", x: 920, y: 160 },
  ],
  edges: [
    ["d1", "d2"],
    ["d1", "d3"],
    ["d2", "d4"],
    ["d3", "d4"],
    ["d4", "d5"],
    ["d4", "d6"],
    ["d5", "d7"],
    ["d6", "d7"],
    ["d7", "d8"],
    ["d8", "d9"],
  ],
};

export const STRUCTURE_DIFFS: StructureDiffItem[] = [
  { text: "Dify 新增「变量聚合」节点", sev: "medium" },
  { text: "HTTP 节点认证方式不同", sev: "high" },
  { text: "路由→IF/ELSE 语法差异", sev: "low" },
];

export const NODE_COMPARISONS: NodeComparison[] = [
  {
    id: "n1",
    type: "llm",
    name: "LLM 主模型",
    cCfg: { model: "gpt-4o", temperature: 0.7 },
    dCfg: { model: "gpt-4o", temperature: 0.7 },
    status: "equivalent",
    diff: [],
  },
  {
    id: "n2",
    type: "knowledge",
    name: "知识库检索",
    cCfg: { dataset: "product_faq", topK: 5 },
    dCfg: { dataset_id: "ds-001", top_k: 5 },
    status: "equivalent",
    diff: [],
  },
  {
    id: "n3",
    type: "code",
    name: "数据预处理",
    cCfg: { language: "python" },
    dCfg: { language: "python3" },
    status: "warning",
    diff: [{ field: "language", coze: "python", dify: "python3", sev: "low" }],
  },
  {
    id: "n4",
    type: "http",
    name: "CRM 接口",
    cCfg: { method: "POST", auth: "headers" },
    dCfg: { method: "POST", auth: "auth_object" },
    status: "error",
    diff: [
      {
        field: "auth",
        coze: "headers",
        dify: "auth object",
        sev: "high",
      },
    ],
  },
];

export const PROMPT_DIFF: PromptDiffData = {
  coze: [
    { ln: 1, text: "# Role", t: "same" },
    { ln: 2, text: "你是专业的智能客服助手。", t: "same" },
    { ln: 3, text: "", t: "same" },
    { ln: 4, text: "# 核心能力", t: "same" },
    { ln: 5, text: "- 产品咨询：回答功能、价格", t: "same" },
    { ln: 6, text: "- 投诉处理：记录并转交人工", t: "removed" },
    { ln: 7, text: "", t: "same" },
    { ln: 8, text: "# 约束", t: "same" },
    { ln: 9, text: "- 不确定时回复「需要确认」", t: "removed" },
    { ln: 10, text: "- 回复不超200字", t: "same" },
  ],
  dify: [
    { ln: 1, text: "# Role", t: "same" },
    { ln: 2, text: "你是专业的智能客服助手。", t: "same" },
    { ln: 3, text: "", t: "same" },
    { ln: 4, text: "# 核心能力", t: "same" },
    { ln: 5, text: "- 产品咨询：回答功能、价格", t: "same" },
    { ln: 6, text: "- 投诉处理：记录并生成工单", t: "added" },
    { ln: 7, text: "", t: "same" },
    { ln: 8, text: "# 约束", t: "same" },
    { ln: 9, text: "- 不确定时回复「让我查询」", t: "added" },
    { ln: 10, text: "- 回复不超200字", t: "same" },
    { ln: 11, text: "- 使用 Markdown 格式", t: "added" },
  ],
  flags: [
    { desc: "投诉→转人工 改为 生成工单", sev: "high", impact: "流程变化" },
    { desc: "不确定措辞变更", sev: "low", impact: "语义等价" },
    { desc: "新增 Markdown 要求", sev: "medium", impact: "格式变化" },
  ],
};

export const VARIABLE_MAPPINGS: VariableMapping[] = [
  { coze: "{{input}}", dify: "{{#sys.query#}}", status: "mapped", auto: true },
  { coze: "{{bot_id}}", dify: "{{#sys.app_id#}}", status: "mapped", auto: true },
  { coze: "{{user_id}}", dify: "{{#sys.user_id#}}", status: "mapped", auto: true },
  {
    coze: "{{knowledge_result}}",
    dify: "{{#knowledge.result#}}",
    status: "mapped",
    auto: false,
  },
  { coze: "{{plugin.weather}}", dify: "—", status: "unmapped", auto: false },
  { coze: "{{user_level}}", dify: "—", status: "unmapped", auto: false },
];

export const PLUGIN_COMPATIBILITY: PluginCompatibilityItem[] = [
  { coze: "天气查询", dify: "Weather Tool", compat: "full" },
  { coze: "网页搜索", dify: "SerpAPI Tool", compat: "full" },
  { coze: "图片生成", dify: "DALL-E Tool", compat: "partial" },
  { coze: "数据库查询", dify: "自定义 Tool", compat: "custom" },
  { coze: "日程管理", dify: "—", compat: "none" },
];

export const TEST_CASES: TestCase[] = [
  {
    id: "t1",
    name: "基础问答",
    input: "产品支持什么OS？",
    cOut: "Win/Mac/Linux…",
    dOut: "Win/Mac/Linux…",
    sim: 0.96,
    status: "pass",
    cL: 1200,
    dL: 980,
  },
  {
    id: "t2",
    name: "投诉处理",
    input: "订单没发货不满意",
    cOut: "非常抱歉…",
    dOut: "非常抱歉…",
    sim: 0.93,
    status: "pass",
    cL: 1500,
    dL: 1100,
  },
  {
    id: "t3",
    name: "多轮上下文",
    input: "查订单→物流？",
    cOut: "ORD-2024…",
    dOut: "请提供订单号？",
    sim: 0.42,
    status: "fail",
    cL: 2100,
    dL: 1800,
    ep: "context_loss",
  },
  {
    id: "t4",
    name: "知识库召回",
    input: "退货政策？",
    cOut: "30天可退…",
    dOut: "30天可退…",
    sim: 0.91,
    status: "pass",
    cL: 1800,
    dL: 1400,
  },
  {
    id: "t5",
    name: "超长输入",
    input: "[2000字]",
    cOut: "理解…",
    dOut: "[ERROR]",
    sim: 0,
    status: "fail",
    cL: 3200,
    dL: 0,
    ep: "api_format",
  },
  {
    id: "t6",
    name: "Session过期",
    input: "[10轮后]方案？",
    cOut: "方案A…",
    dOut: "哪个？",
    sim: 0.38,
    status: "fail",
    cL: 2500,
    dL: 2200,
    ep: "context_loss",
  },
];

export const ERROR_PATTERNS: ErrorPattern[] = [
  {
    id: "ep1",
    name: "上下文丢失",
    key: "context_loss",
    count: 2,
    sev: "critical",
    desc: "Dify 多轮对话丢失上下文",
    fix: "检查 conversation_variables 和 memory 窗口",
    tests: ["t3", "t6"],
  },
  {
    id: "ep2",
    name: "API格式不兼容",
    key: "api_format",
    count: 1,
    sev: "high",
    desc: "超长输入处理不同",
    fix: "增加输入长度校验",
    tests: ["t5"],
  },
];

export const KNOWLEDGE_BASES: KnowledgeBaseRecord[] = [
  { name: "产品FAQ", cC: 156, dC: 162, match: 0.91, emb: "一致", ok: true },
  { name: "操作手册", cC: 89, dC: 89, match: 0.95, emb: "一致", ok: true },
  { name: "故障排除", cC: 234, dC: 198, match: 0.72, emb: "不一致", ok: false },
  { name: "定价文档", cC: 45, dC: 45, match: 0.98, emb: "一致", ok: true },
];

export const CANARY_STAGES: CanaryStage[] = [
  { pct: 0, label: "准备", st: "done", ts: "03/10" },
  { pct: 5, label: "5%", st: "done", ts: "03/10" },
  { pct: 20, label: "20%", st: "active", ts: "03/11" },
  { pct: 50, label: "50%", st: "pending", ts: "—" },
  { pct: 100, label: "100%", st: "pending", ts: "—" },
];

export const ROLLBACK_VERSIONS: RollbackVersion[] = [
  { ver: "v1.0", ts: "03-08", st: "archived", score: 78.2 },
  { ver: "v1.2", ts: "03-10", st: "rollback", score: 91.7 },
  { ver: "v1.3", ts: "03-11", st: "active", score: 93.4 },
];

export const REVIEW_QUEUE: ReviewItem[] = [
  {
    id: "r1",
    testId: "t6",
    q: "Session过期",
    sim: 0.38,
    cS: "方案A…",
    dS: "哪个方案？",
    verdict: null,
  },
  {
    id: "r2",
    testId: "t2",
    q: "投诉措辞差异",
    sim: 0.93,
    cS: "给您带来了不便",
    dS: "给您带来不便",
    verdict: "equivalent",
  },
  {
    id: "r3",
    testId: "t4",
    q: "知识库召回",
    sim: 0.91,
    cS: "30天内可退换",
    dS: "30天内可退",
    verdict: null,
  },
];

export const SANDBOX_METRICS: LiveMetric[] = [
  { label: "请求数", coze: "142", dify: "142" },
  { label: "平均延迟", coze: "1.2s", dify: "0.9s" },
  { label: "错误率", coze: "0.7%", dify: "1.4%" },
];
